version: '3.1'

services:

  api-transaction:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: api-transaction
    container_name: api-transaction
    network_mode: bridge
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo
    network_mode: bridge
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: transaction
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: springboot
    volumes:
      - ./populate-db.js:/docker-entrypoint-initdb.d/populate-db.js:ro


  mongo-express:
    image: mongo-express
    network_mode: bridge
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: springboot
      ME_CONFIG_MONGODB_URL: mongodb://admin:springboot@mongo:27017/
    links:
      - mongo  