server:
  servlet:
    context-path: /api-transaction

spring:
  data:
    mongodb:
      uri: mongodb://admin:springboot@localhost:27017/
      database: transaction
      authentication-database: admin
